name: realdex_drill

task_name: drill

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [2048, 3]
      type: point_cloud
    start_pos:
      shape: [3]
      type: low_dim
    goal_pos:
      shape: [3]
      type: low_dim
    start_rot:
      shape: [4]
      type: low_dim
    goal_rot:
      shape: [4]
      type: low_dim
  action:
    shape: [22]

env_runner: null

dataset:
  _target_: diffusion_policy_3d.dataset.realdex_dataset.RealDexDataset
  zarr_path: data/realdex_drill.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
  point_cloud_key: point_cloud
  obs_keys: [point_cloud, start_pos, goal_pos, start_rot, goal_rot]
  fallback_state_key: state
  state_slices:
    start_pos: [0, 3]
    goal_pos: [3, 6]
    start_rot: [6, 10]
    goal_rot: [10, 14]
